[graph]
all-features = true


[licenses]
allow = [
  "Apache-2.0",
  "LGPL-3.0-only", # malachite
  "MIT",
  "MPL-2.0",
  "Unicode-3.0",   # unicode-ident
  "Zlib",          # foldhash
]
confidence-threshold = 0.8
exceptions = []


[bans]
multiple-versions = "deny"


[sources]
unknown-registry = "deny"
unknown-git = "deny"
