[graph]
all-features = true


[output]
feature-depth = 1


[licenses]
allow = ["MIT", "MPL-2.0"]
# confidence-threshold = 0.8
exceptions = [{ allow = ["Unicode-3.0"], crate = "unicode-ident" }]


[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"


[sources]
unknown-registry = "deny"
unknown-git = "deny"
