//! Implementations for tuples, up to a finite size.

use {
    crate::{
        ast_size::AstSize,
        error,
        exhaust::Exhaust,
        max::{Max, MaybeDecidable, MaybeOverflow},
        pseudorandom::Pseudorandom,
        test_impls_for,
        value_size::ValueSize,
    },
    core::{hint::unreachable_unchecked, iter},
    rand_core::RngCore,
};

#[cfg(test)]
use core::convert::Infallible;

/// An iterator that starts inactive,
/// remains active until it has been exhausted,
/// and then may be started again.
#[derive(Debug, Default)]
pub enum MaybeIterator<T: Exhaust> {
    /// If and only if there is an active iterator that has not returned `None`.
    Active {
        /// The internal exhaustive iterator over `T`.
        iter: T::Exhaust,
    },
    /// Either not yet started or just finished.
    #[default]
    Inactive,
}

/// An iterator that starts inactive,
/// remains active until it has been exhausted
/// (caching the most recent item until asked to advance),
/// and then may be started again.
#[derive(Debug, Default)]
pub enum CachingIterator<T: Clone + Exhaust> {
    /// If and only if there is an active iterator that has not returned `None`.
    Active {
        /// The value-size of `T`s generated by `iter`.
        size: usize,
        /// The internal exhaustive iterator over `T`.
        iter: T::Exhaust,
        /// The most recent item, if any.
        cache: Option<T>,
    },
    /// Either not yet started or just finished.
    #[default]
    Inactive,
}

/// Inductively create a nested tuple,
/// then flatten each generated value.
#[derive(Debug)]
pub struct FlattenNestedIterator<N: NestedIterator> {
    /// An iterator producing nested tuples of any given size.
    nested_iterator: N,
    /// The total value-size of each tuple as a whole.
    total_size: usize,
}

/// Produce a nested tuple of any given size.
pub trait NestedIterator {
    /// The nested tuple type to be produced.
    type Item;
    /// Produce the next nested tuple of a given size.
    /// TODO: move `remaining_size` to `self` instead! It shouldn't change until exhausted!
    fn nested_next(&mut self, remaining_size: usize) -> Option<Self::Item>;
    /// Assert that all downstream iterators are inactive (e.g. from having been restarted).
    #[cfg(debug_assertions)]
    fn debug_assert_all_inactive(&self);
}

impl<T: Exhaust> MaybeIterator<T> {
    /// Get the next item in an existing iterator if we're already using one.
    /// If there was an iterator, but it's now empty, drop it and return `None`.
    /// If there was no iterator in here in the first place, try to start one;
    /// then, if and only if that succeeds *and* it is non-empty, return its first item.
    /// # Invariant
    /// If this function returns `Some`, then
    /// this `enum` is `MaybeIterator::Active { .. }` afteward;
    /// if not, this is `MaybeIterator::Inactive` afteward
    /// (either from clearing after an iterator ended or from failing to start a new one).
    #[inline]
    pub(crate) fn next_or_new(&mut self, remaining_size: usize) -> Option<T> {
        match *self {
            Self::Active { ref mut iter } => iter.next().or_else(|| {
                *self = Self::Inactive;
                None
            }),
            Self::Inactive => {
                // Unlike non-final fields, the field at the end of the tuple
                // has to be *exactly* `remaining_size` to work.
                if let Ok(mut iter) = T::exhaust(remaining_size)
                    && let Some(next) = iter.next()
                {
                    *self = Self::Active { iter };
                    Some(next)
                } else {
                    None
                }
            }
        }
    }
}

impl<T: Exhaust> NestedIterator for MaybeIterator<T> {
    type Item = T;
    #[inline]
    fn nested_next(&mut self, remaining_size: usize) -> Option<Self::Item> {
        self.next_or_new(remaining_size)
    }

    #[inline]
    #[cfg(debug_assertions)]
    fn debug_assert_all_inactive(&self) {
        match *self {
            Self::Inactive => {}
            Self::Active { .. } => {
                panic!(
                    "Expected all downstream iterators to be inactive, but the final `MaybeIterator` was active"
                )
            }
        }
    }
}

impl<T: Clone + Exhaust> CachingIterator<T> {
    /// Regardless of whether there's currently any value cached,
    /// advance this iterator (if possible) and update the cache accordingly.
    /// If the iterator could not be advanced, use the provided argument
    /// to restart at another size (if any, otherwise immediately failing),
    /// then loop downward from that provided value (if any)
    /// until a non-empty iterator could be created,
    /// failing if that loop ends before succeeding.
    #[inline]
    pub fn fill_cache_with_next_value(
        &mut self,
        maybe_remaining_size: Option<usize>,
    ) -> Option<()> {
        if let Self::Active {
            ref mut iter,
            ref mut cache,
            ..
        } = *self
        {
            if let Some(next) = iter.next() {
                *cache = Some(next);
                return Some(());
            }
            *self = Self::Inactive;
        }
        self.new_iterator_with_size_at_most(maybe_remaining_size?)
    }

    /// Check if this iterator has a value already cached,
    /// without actually returning the value (to avoid lifetime extension).
    #[inline]
    pub const fn has_value_cached(&self) -> bool {
        matches!(
            self,
            Self::Active {
                cache: Some(..),
                ..
            },
        )
    }

    /// Start a new iterator at the provided size;
    /// if it produces a value, cache it and return;
    /// if not, iteratively reduce size and create new iterators until one does,
    /// or return `None` if we exhaust all sizes from the argument down to zero.
    #[inline]
    fn new_iterator_with_size_at_most(&mut self, remaining_size: usize) -> Option<()> {
        for size in (0..=remaining_size).rev() {
            // TODO: Binary search for reachability, then linear descent?
            let Ok(mut iter) = T::exhaust(size) else {
                continue;
            };
            let Some(cached) = iter.next() else { continue };
            *self = Self::Active {
                size,
                iter,
                cache: Some(cached),
            };
            return Some(());
        }
        *self = Self::Inactive;
        None
    }
}

impl<T: Clone + Exhaust, Tail: NestedIterator> NestedIterator for (CachingIterator<T>, Tail) {
    type Item = (T, Tail::Item);
    #[inline]
    fn nested_next(&mut self, remaining_size: usize) -> Option<Self::Item> {
        // Syntactic operation only: split `self` into `head` and `tail`:
        let (ref mut head_iter, ref mut tail_iter) = *self;

        // Each element of the tuple (left to right) should keep the same cached value
        // until the elements to the right of it have been fully exhausted,
        // at which point (and ONLY at which point) it should advance with all downstream restarted.
        // TODO: In practice, this particular `if` condition is only ever satisfied
        // when starting the overall iterator; maybe consider removing the `Inactive` variant
        // and moving the startup logic into the initialization (which then could fail)
        // so we could remove this and improve efficiency in this very hot loop?
        if !head_iter.has_value_cached() {
            #[cfg(debug_assertions)]
            {
                // Another logical invariant arises from the logic around these iterators
                // and the structure of the below loop (which in turn relies on this invariant):
                // **anytime one iterator is `Inactive`, so are all those after it.**
                let () = tail_iter.debug_assert_all_inactive();
            }
            // Fill the cached value to establish the loop invariant below,
            // or exit with `None` if the iterator is empty:
            let () = head_iter.fill_cache_with_next_value(Some(remaining_size))?;
        }
        // Duh, but worth checking anyway (at least until v1.0):
        debug_assert!(head_iter.has_value_cached());

        // LOOP INVARIANT (established above):
        // `head_iter` is `Active` with a value in its `cache` (as `Some(..)`).
        // If this fails at any point, this function returns `None`.
        loop {
            // Check the loop invariant (in debug builds only):
            debug_assert!(head_iter.has_value_cached());

            // Get the cached head value, which we know exists b/c of the loop invariant above:
            let CachingIterator::Active {
                size: head_size,
                cache: Some(ref head_cached),
                ..
            } = *head_iter
            else {
                // SAFETY:
                // Just established above (before the loop),
                // and the end of the loop re-establishes the invariant as well.
                unsafe { unreachable_unchecked() }
            };

            // Subtract the head size from the remaining size (for the tail):
            // Note that this isn't using `checked_sub`, since _a priori_
            // the head can never be larger than `remaining_size`.
            // However, if this invariant were to be violated,
            // tests would pick it up, since Rust's `-` panics on overflow in debug builds.
            #[expect(clippy::arithmetic_side_effects, reason = "Intentional: see above.")]
            let tail_size = remaining_size - head_size;

            if let Some(tail) = tail_iter.nested_next(tail_size) {
                return Some((head_cached.clone(), tail));
            }

            // Check that all downstream iterators are inactive and ready to be restarted:
            #[cfg(debug_assertions)]
            let () = tail_iter.debug_assert_all_inactive();

            // Then update the cache with the next value for this index of the tuple,
            // implicitly restarting all downstream iterators (checked above):
            let () = head_iter.fill_cache_with_next_value(head_size.checked_sub(1))?;
        }
    }

    #[inline]
    #[cfg(debug_assertions)]
    fn debug_assert_all_inactive(&self) {
        let (ref head, ref tail) = *self;
        match *head {
            CachingIterator::Active {
                size, ref cache, ..
            } => panic!(
                "Expected all downstream iterators to be inactive, but a caching iterator was active with size {size:?} and cache {cache:?}",
            ),
            CachingIterator::Inactive => tail.debug_assert_all_inactive(),
        }
    }
}

#[expect(clippy::missing_trait_methods, reason = "would take years")]
impl<N: NestedIterator> Iterator for FlattenNestedIterator<N> {
    type Item = N::Item;
    #[inline]
    fn next(&mut self) -> Option<Self::Item> {
        self.nested_iterator.nested_next(self.total_size)
    }
}

impl AstSize for () {
    const MAX_AST_SIZE: MaybeDecidable<Max<MaybeOverflow<usize>>> =
        MaybeDecidable::Decidable(Max::Finite(MaybeOverflow::Contained(0)));
    const MAX_EXPECTED_AST_SIZE: MaybeDecidable<Max<f32>> =
        MaybeDecidable::Decidable(Max::Finite(0.));
    #[inline]
    fn ast_size(&self) -> MaybeOverflow<usize> {
        MaybeOverflow::Contained(0)
    }
}

impl ValueSize for () {
    const MAX_VALUE_SIZE: MaybeDecidable<Max<MaybeOverflow<usize>>> =
        MaybeDecidable::Decidable(Max::Finite(MaybeOverflow::Contained(0)));
    #[inline]
    fn value_size(&self) -> MaybeOverflow<usize> {
        MaybeOverflow::Contained(0)
    }
}

impl Exhaust for () {
    type Exhaust = iter::Once<Self>;
    #[inline]
    fn exhaust(value_size: usize) -> Result<Self::Exhaust, error::UnreachableSize> {
        if value_size == 0 {
            Ok(iter::once(()))
        } else {
            Err(error::UnreachableSize)
        }
    }
}

impl Pseudorandom for () {
    #[inline]
    fn pseudorandom<Rng: RngCore>(
        _expected_ast_size: f32,
        _rng: &mut Rng,
    ) -> Result<Self, error::Uninstantiable> {
        Ok(())
    }
}

pbt_macro::impl_non_empty_tuples!();

/// Let's say we're iterating over fields in a tuple,
/// and we know the maximum size of each field (unless undecidable, overflowed, etc.).
/// Let's further suppose that we have an overall goal size in mind for the whole tuple.
/// Then if we split the size evenly over all fields, it would be applied unevenly in general:
/// some fields are uninstantiable, and some have a finite size lower than the even split.
/// This `struct` holds the result of counting those quantities.
struct FullAndPartialFields {
    /// The number of fields that could generate at least the requested expected AST size.
    n_full_fields: usize,
    /// The sum of the sizes of each field that could not generate the requested AST size.
    sum_of_partial_sizes: f32,
}

/// Let's say we're iterating over fields in a tuple,
/// and we know the maximum size of each field (unless undecidable, overflowed, etc.).
/// Let's further suppose that we have an overall goal size in mind for the whole tuple.
/// Then if we split the size evenly over all fields, it would be applied unevenly in general:
/// some fields are uninstantiable, and some have a finite size lower than the even split.
/// This function counts those quantities.
#[inline]
const fn full_and_partial_fields(
    even_split: f32,
    max_expected_ast_sizes: &[MaybeDecidable<Max<f32>>],
) -> FullAndPartialFields {
    match *max_expected_ast_sizes {
        [] => FullAndPartialFields {
            n_full_fields: 0,
            sum_of_partial_sizes: 0.,
        },
        [ref head, ref tail @ ..] => {
            let mut rec = full_and_partial_fields(even_split, tail);
            match *head.at_most() {
                Max::Uninstantiable => {}
                Max::Finite(max) if max < even_split => rec.sum_of_partial_sizes += max,
                #[expect(
                    clippy::arithmetic_side_effects,
                    reason = "If we overflow a `usize` by incremental addition, something has gone horribly wrong."
                )]
                Max::Finite(_) | Max::Infinite => rec.n_full_fields += 1,
            }
            rec
        }
    }
}

/*
use {
    crate::{
        ast_size::AstSize,
        error,
        exhaust::Exhaust,
        max::{Max, MaybeDecidable, MaybeOverflow},
        pseudorandom::Pseudorandom,
        value_size::ValueSize,
    },
    rand_core::RngCore,
};

/// Count the number of type parameters in a generic tuple.
macro_rules! n_params {
    () => { 0 };
    ($head:ident, $($tail:tt,)*) => {
        1 + n_params!($($tail,)*)
    };
}

/// Implement a specific tuple of generic types.
macro_rules! impl_tuple {
    ($($type_param:ident,)*) => {
        impl<$($type_param: AstSize,)*> AstSize for ($($type_param,)*) {
            const MAX_AST_SIZE: MaybeDecidable<Max<MaybeOverflow<usize>>> = {
                let acc = MaybeDecidable::Decidable(Max::Finite(MaybeOverflow::Contained(0_usize)));
                $(
                    let acc = acc.product(&$type_param::MAX_AST_SIZE);
                )*
                acc
            };

            const MAX_EXPECTED_AST_SIZE: MaybeDecidable<Max<f32>> = {
                let acc = MaybeDecidable::Decidable(Max::Finite(0_f32));
                $(
                    let acc = acc.product(&$type_param::MAX_EXPECTED_AST_SIZE);
                )*
                acc
            };

            #[inline]
            fn ast_size(&self) -> MaybeOverflow<usize> {
                #[expect(non_snake_case, reason = "automatic")]
                let ($(ref $type_param,)*) = *self;
                let acc = 0_usize;
                $(
                    let MaybeOverflow::Contained(acc) = $type_param.ast_size().plus(acc) else {
                        return MaybeOverflow::Overflow
                    };
                )*
                MaybeOverflow::Contained(acc)
            }
        }

        impl<$($type_param: ValueSize,)*> ValueSize for ($($type_param,)*) {
            const MAX_VALUE_SIZE: MaybeDecidable<Max<MaybeOverflow<usize>>> = {
                let acc = MaybeDecidable::Decidable(Max::Finite(MaybeOverflow::Contained(0_usize)));
                $(
                    let acc = acc.product(&$type_param::MAX_VALUE_SIZE);
                )*
                acc
            };

            #[inline]
            fn value_size(&self) -> MaybeOverflow<usize> {
                #[expect(non_snake_case, reason = "automatic")]
                let ($(ref $type_param,)*) = *self;
                let acc = 0_usize;
                $(
                    let MaybeOverflow::Contained(acc) = $type_param.value_size().plus(acc) else {
                        return MaybeOverflow::Overflow
                    };
                )*
                MaybeOverflow::Contained(acc)
            }
        }

        impl<$($type_param: Pseudorandom,)*> Pseudorandom for ($($type_param,)*) {
            #[inline]
            fn pseudorandom<Rng: RngCore>(
                expected_ast_size: f32,
                rng: &mut Rng,
            ) -> Result<Self, error::Uninstantiable> {
                #![expect(clippy::as_conversions, clippy::cast_precision_loss, reason = "OK")]

                const N_PARAMS_USIZE: usize = n_params!($($type_param,)*);
                const N_PARAMS: f32 = N_PARAMS_USIZE as f32;

                let even_split = expected_ast_size / N_PARAMS;
                let FullAndPartialFields { n_full_fields, sum_of_partial_sizes } = full_and_partial_fields(
                    even_split,
                    &[$($type_param::MAX_EXPECTED_AST_SIZE,)*],
                );
                // Really, we should iterate until we reach a fixed point,
                // but this will work very well as a good-enough approximation,
                // and the throughput trade-off is a no-brainer.
                let size_per_element = (expected_ast_size - sum_of_partial_sizes) / (n_full_fields as f32);

                Ok(($($type_param::pseudorandom(size_per_element, rng)?,)*))
            }
        }

        impl<$($type_param: Exhaust,)*> Exhaust for ($($type_param,)*) {
            #[inline]
            fn exhaust(value_size: usize) -> Result<impl Iterator<Item = Self>, error::UnreachableSize> {

                #[expect(non_snake_case, reason = "automatic")]
                struct Tuple<$($type_param: Exhaust,)*> { $($type_param: $type_param,)* }

                impl<$($type_param: Exhaust,)*> Iterator for Tuple<$($type_param,)*> {
                    type Item = ($($type_param,)*);

                    #[inline]
                    fn next(&mut self) -> Option<Self::Item> {
                        /*
                        Here's the algorithm in plain English:
                          + Each field in the output tuple has two fields in this `struct`:
                          |   + An iterator field;
                          |   + A cache field.
                          + All cache fields start at `None`.
                          + The main loop iterates forward over elements:
                          |   + If a cache is `None`, try to fill it by advancing its iterator.
                          |   |   + If *this* fails, erase the *last* element's cache (set to `None`) and start over.
                          |   |   |   + If there's no last element (i.e. the first failed), return `None` overall.
                          |   + If we've reached this point, the cache is `Some(..)`, so extract its value.
                          + If we manage to iterate over every element, return the tuple of all extracted caches.
                        */
                    }
                }
            }
        }
    };
}

/// Implement every tuple up to and including this full sequence of generic types.
macro_rules! impl_tuples {
    (@internal [$($acc:tt,)*]) => { };
    (@internal [$($acc:tt,)*] $type_param:ident, $($rest:tt,)*) => {
        impl_tuple!($($acc,)* $type_param,);
        impl_tuples!(@internal [$($acc,)* $type_param,] $($rest,)*);
    };
    ($($type_param:ident,)*) => {
        impl_tuples!(@internal [] $($type_param,)*);
    };
}

impl_tuples!(
    T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15,
    T16, // T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32,
);
*/

test_impls_for!((), unit);
test_impls_for!((Infallible,), singleton_infallible);
test_impls_for!(((),), singleton_unit);
test_impls_for!((bool,), singleton_bool);
test_impls_for!((u8,), singleton_u8);
test_impls_for!((u128,), singleton_u128);
test_impls_for!((Infallible, Infallible), pair_infallible);
test_impls_for!(((), ()), pair_unit);
test_impls_for!((bool, bool), pair_bool);
test_impls_for!((u8, u8), pair_u8);
test_impls_for!((Infallible, Infallible, Infallible), triple_infallible);
test_impls_for!(((), (), ()), triple_unit);
test_impls_for!((bool, bool, bool), triple_bool);
test_impls_for!((u8, u8, u8), triple_u8);
test_impls_for!((Infallible, u8, u8), triple_infallible_u8_u8);
test_impls_for!((u8, Infallible, u8), triple_u8_infallible_u8);
test_impls_for!((u8, u8, Infallible), triple_u8_u8_infallible);
test_impls_for!((Infallible, (), u8), triple_infallible_unit_u8);
test_impls_for!((Infallible, u8, ()), triple_infallible_u8_unit);
test_impls_for!((u8, Infallible, ()), triple_u8_infallible_unit);
test_impls_for!(((), Infallible, u8), triple_unit_infallible_u8);
test_impls_for!((u8, (), Infallible), triple_u8_unit_infallible);
test_impls_for!(((), u8, Infallible), triple_unit_u8_infallible);
test_impls_for!((u8, u8, u8, u8), quadruple_u8);
test_impls_for!((u8, u8, u8, u8, u8), quintuple_u8);

#[cfg(test)]
#[expect(
    clippy::unwrap_used,
    reason = "Tests are supposed to fail if they don't behave as expected."
)]
mod test {
    use {
        super::*,
        crate::exhaust::{Exhaust, exhaust},
        alloc::{vec, vec::Vec},
    };

    extern crate alloc;

    #[test]
    fn maybe_iterator_invariant_when_inactive() {
        for remaining_size in 0..1_000 {
            let mut input = MaybeIterator::<u8>::Inactive;
            match input.next_or_new(remaining_size) {
                Some(_) => assert!(matches!(input, MaybeIterator::Active { .. })),
                None => assert!(matches!(input, MaybeIterator::Inactive)),
            }
        }
    }

    #[test]
    fn maybe_iterator_invariant_when_active() {
        for (once_active, remaining_size) in exhaust::<(u8, usize)>().take(1_000) {
            let mut input = MaybeIterator::<u8>::Active {
                iter: iter::once(once_active),
            };
            match input.next_or_new(remaining_size) {
                Some(_) => assert!(matches!(input, MaybeIterator::Active { .. })),
                None => assert!(matches!(input, MaybeIterator::Inactive)),
            }
        }
    }

    #[test]
    fn caching_iterator_invariant_when_inactive() {
        for remaining_size in exhaust::<Option<usize>>().take(1_000) {
            let mut input = CachingIterator::<u8>::Inactive;
            match input.fill_cache_with_next_value(remaining_size) {
                Some(_) => assert!(input.has_value_cached()),
                None => assert!(matches!(input, CachingIterator::Inactive)),
            }
        }
    }

    #[test]
    fn caching_iterator_invariant_when_active() {
        for (remaining_size, once_active, cache) in
            exhaust::<(Option<usize>, u8, Option<u8>)>().take(1_000)
        {
            let mut input = CachingIterator::Active {
                size: usize::from(once_active),
                cache,
                iter: iter::once(once_active),
            };
            match input.fill_cache_with_next_value(remaining_size) {
                Some(_) => assert!(input.has_value_cached()),
                None => assert!(matches!(input, CachingIterator::Inactive)),
            }
        }
    }

    #[test]
    fn singleton_of_u8_size_0() {
        assert_eq!(
            <(u8,) as Exhaust>::exhaust(0).unwrap().collect::<Vec<_>>(),
            vec![(0,)]
        );
    }

    #[test]
    fn singleton_of_u8_size_1() {
        assert_eq!(
            <(u8,) as Exhaust>::exhaust(1).unwrap().collect::<Vec<_>>(),
            vec![(1,)]
        );
    }

    #[test]
    fn singleton_of_u8_size_2() {
        assert_eq!(
            <(u8,) as Exhaust>::exhaust(2).unwrap().collect::<Vec<_>>(),
            vec![(2,)]
        );
    }

    #[test]
    fn singleton_of_u8_size_3() {
        assert_eq!(
            <(u8,) as Exhaust>::exhaust(3).unwrap().collect::<Vec<_>>(),
            vec![(3,)]
        );
    }

    #[test]
    fn nested_pair_of_u8_size_0() {
        let mut nest = FlattenNestedIterator {
            nested_iterator: (
                CachingIterator::<u8>::Inactive,
                MaybeIterator::<u8>::Inactive,
            ),
            total_size: 0,
        };
        assert_eq!(nest.next(), Some((0, 0)));
        assert!(
            matches!(
                nest,
                FlattenNestedIterator {
                    nested_iterator: (
                        CachingIterator::Active {
                            size: 0,
                            cache: Some(_),
                            ..
                        },
                        MaybeIterator::Active { .. },
                    ),
                    total_size: 0
                },
            ),
            "{nest:#?}",
        );
        assert_eq!(nest.next(), None);
        assert!(
            matches!(
                nest,
                FlattenNestedIterator {
                    nested_iterator: (CachingIterator::Inactive, MaybeIterator::Inactive),
                    total_size: 0
                },
            ),
            "{nest:#?}",
        );
    }

    #[test]
    fn nested_pair_of_u8_size_1() {
        let mut nest = FlattenNestedIterator {
            nested_iterator: (
                CachingIterator::<u8>::Inactive,
                MaybeIterator::<u8>::Inactive,
            ),
            total_size: 1,
        };
        assert_eq!(nest.next(), Some((1, 0)));
        assert!(
            matches!(
                nest,
                FlattenNestedIterator {
                    nested_iterator: (
                        CachingIterator::Active {
                            size: 1,
                            cache: Some(_),
                            ..
                        },
                        MaybeIterator::Active { .. },
                    ),
                    total_size: 1,
                },
            ),
            "{nest:#?}",
        );
        assert_eq!(nest.next(), Some((0, 1)));
        assert!(
            matches!(
                nest,
                FlattenNestedIterator {
                    nested_iterator: (
                        CachingIterator::Active {
                            size: 0,
                            cache: Some(_),
                            ..
                        },
                        MaybeIterator::Active { .. },
                    ),
                    total_size: 1,
                },
            ),
            "{nest:#?}",
        );
        assert_eq!(nest.next(), None);
        assert!(
            matches!(
                nest,
                FlattenNestedIterator {
                    nested_iterator: (CachingIterator::Inactive, MaybeIterator::Inactive),
                    total_size: 1,
                },
            ),
            "{nest:#?}",
        );
    }

    #[test]
    fn nested_pair_of_u8_size_2() {
        let nest = FlattenNestedIterator {
            nested_iterator: (
                CachingIterator::<u8>::Inactive,
                MaybeIterator::<u8>::Inactive,
            ),
            total_size: 2,
        };
        assert_eq!(nest.collect::<Vec<_>>(), vec![(2, 0), (1, 1), (0, 2)]);
    }

    #[test]
    fn nested_pair_of_u8_size_3() {
        let nest = FlattenNestedIterator {
            nested_iterator: (
                CachingIterator::<u8>::Inactive,
                MaybeIterator::<u8>::Inactive,
            ),
            total_size: 3,
        };
        assert_eq!(
            nest.collect::<Vec<_>>(),
            vec![(3, 0), (2, 1), (1, 2), (0, 3)]
        );
    }

    #[test]
    fn pair_of_u8_size_0() {
        assert_eq!(
            <(u8, u8) as Exhaust>::exhaust(0)
                .unwrap()
                .collect::<Vec<_>>(),
            vec![(0, 0)],
        );
    }

    #[test]
    fn pair_of_u8_size_1() {
        assert_eq!(
            <(u8, u8) as Exhaust>::exhaust(1)
                .unwrap()
                .collect::<Vec<_>>(),
            vec![(1, 0), (0, 1)],
        );
    }

    #[test]
    fn pair_of_u8_size_2() {
        assert_eq!(
            <(u8, u8) as Exhaust>::exhaust(2)
                .unwrap()
                .collect::<Vec<_>>(),
            vec![(2, 0), (1, 1), (0, 2)],
        );
    }

    #[test]
    fn pair_of_u8_size_3() {
        assert_eq!(
            <(u8, u8) as Exhaust>::exhaust(3)
                .unwrap()
                .collect::<Vec<_>>(),
            vec![(3, 0), (2, 1), (1, 2), (0, 3)],
        );
    }

    #[test]
    fn triple_of_u8_size_0() {
        assert_eq!(
            <(u8, u8, u8) as Exhaust>::exhaust(0)
                .unwrap()
                .collect::<Vec<_>>(),
            vec![(0, 0, 0)],
        );
    }

    #[test]
    fn triple_of_u8_size_1() {
        assert_eq!(
            <(u8, u8, u8) as Exhaust>::exhaust(1)
                .unwrap()
                .collect::<Vec<_>>(),
            vec![(1, 0, 0), (0, 1, 0), (0, 0, 1)],
        );
    }

    #[test]
    fn triple_of_u8_size_2() {
        assert_eq!(
            <(u8, u8, u8) as Exhaust>::exhaust(2)
                .unwrap()
                .collect::<Vec<_>>(),
            vec![
                (2, 0, 0),
                (1, 1, 0),
                (1, 0, 1),
                (0, 2, 0),
                (0, 1, 1),
                (0, 0, 2),
            ],
        );
    }

    #[test]
    fn triple_of_u8_size_3() {
        assert_eq!(
            <(u8, u8, u8) as Exhaust>::exhaust(3)
                .unwrap()
                .collect::<Vec<_>>(),
            vec![
                (3, 0, 0),
                (2, 1, 0),
                (2, 0, 1),
                (1, 2, 0),
                (1, 1, 1),
                (1, 0, 2),
                (0, 3, 0),
                (0, 2, 1),
                (0, 1, 2),
                (0, 0, 3),
            ],
        );
    }

    #[test]
    fn triple_bool_u8_u16_size_3() {
        assert_eq!(
            <(bool, u8, u16) as Exhaust>::exhaust(3)
                .unwrap()
                .collect::<Vec<_>>(),
            vec![
                (true, 2, 0),
                (true, 1, 1),
                (true, 0, 2),
                (false, 3, 0),
                (false, 2, 1),
                (false, 1, 2),
                (false, 0, 3),
            ],
        );
    }
}
